name: Photophugly
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3749274
title: A Photo Phugly adventure in imaging
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3263566
  lightness: 0
  saturation: 0.5638298
  rhythmicContrast: 0.2626108
purpose: []
